# Generated by Django 4.2.1 on 2023-05-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0002_apartment_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='Type',
        ),
        migrations.AddField(
            model_name='apartment',
            name='aprt_type',
            field=models.CharField(blank=True, choices=[('option1', '1BHK'), ('option2', '2BHK'), ('option3', '3BHK')], max_length=20),
        ),
    ]
