# Generated by Django 4.2.1 on 2023-05-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0003_remove_apartment_type_apartment_aprt_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='author',
            new_name='room_features',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='email',
        ),
    ]
