# Generated by Django 4.2.1 on 2023-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0004_rename_author_apartment_room_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='aprt_type',
            field=models.CharField(blank=True, choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=20),
        ),
    ]
