# Generated by Django 4.2.1 on 2023-05-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0005_alter_apartment_aprt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='picture',
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_images')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logsin.apartment')),
            ],
        ),
    ]
