# Generated by Django 4.2.1 on 2023-05-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0006_remove_apartment_picture_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ApartmentImage',
        ),
    ]
