# Generated by Django 4.2.1 on 2023-05-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0007_apartment_picture_delete_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='aprt_type',
            field=models.CharField(blank=True, choices=[('Apartment_Type: 1BHK', '1BHK'), ('Apartment_Type: 2BHK', '2BHK'), ('Apartment_Type: 3BHK', '3BHK')], max_length=20),
        ),
    ]
