# Generated by Django 4.2.1 on 2023-06-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0008_alter_apartment_aprt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='description',
        ),
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.TextField(default='Gaindakot,Nawalpur'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_features',
            field=models.CharField(max_length=30),
        ),
    ]
