# Generated by Django 4.2.1 on 2023-06-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsin', '0009_remove_apartment_description_apartment_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(default='Gaindakot,Nawalpur', max_length=100),
        ),
    ]
